### PR TITLE
Spec proposal for Metadata Reflection API

### PR DESCRIPTION
**Pull request by rbuckton**
Spec proposal for Metadata Reflection API (in Markdown this time)

### CODE REVIEW

**Comment by jonathandturner** [comment]
Cool.  It's great to have this kind of detail.

Would be great to start with the set of motivating test cases that we're basing the design on.  I know we've done this in person, but since we have four different groups working together now and it's helpful groundwork.

**Comment by rbuckton** [comment]
@jonathandturner, I'm putting that together as well and should have an update shortly.

**Comment by EisenbergEffect** [comment]
@rbuckton Would using `Symbol` be allowable for metadataKey in the proposed apis?

**Comment by EisenbergEffect** [comment]
Seems like defining well known Symbols for type metadata, rather than special strings, might be something useful.

**Comment by rbuckton** [comment]
@EisenbergEffect Yes, any valid property key (via the [ToPropertyKey](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-topropertykey) abstract operation).

**Pull request merged**
